/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mega;

import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class FTW extends javax.swing.JFrame {

    /**
     * Creates new form FTW
     */
    
    int acertos= 0, aposta = 0, quadra = 0, quina = 0, mega = 0, acertostotal = 0, cartoes = 0;
    double vtotal = 0.0;
    
    public FTW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sorteioofc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cartao = new javax.swing.JTextField();
        seis = new javax.swing.JRadioButton();
        sete = new javax.swing.JRadioButton();
        oito = new javax.swing.JRadioButton();
        nove = new javax.swing.JRadioButton();
        dez = new javax.swing.JRadioButton();
        quinze = new javax.swing.JRadioButton();
        catorze = new javax.swing.JRadioButton();
        treze = new javax.swing.JRadioButton();
        doze = new javax.swing.JRadioButton();
        onze = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        result = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vgasto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Numeros Sorteados:");

        a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        a2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        a3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        a4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        a5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        a6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout sorteioofcLayout = new javax.swing.GroupLayout(sorteioofc);
        sorteioofc.setLayout(sorteioofcLayout);
        sorteioofcLayout.setHorizontalGroup(
            sorteioofcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sorteioofcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sorteioofcLayout.setVerticalGroup(
            sorteioofcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteioofcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sorteioofcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Cartões:");

        cartao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonGroup1.add(seis);
        seis.setText("Seis");
        seis.setPreferredSize(new java.awt.Dimension(70, 20));
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        buttonGroup1.add(sete);
        sete.setText("Sete");
        sete.setPreferredSize(new java.awt.Dimension(70, 20));
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });

        buttonGroup1.add(oito);
        oito.setText("Oito");
        oito.setPreferredSize(new java.awt.Dimension(70, 20));

        buttonGroup1.add(nove);
        nove.setText("Nove");
        nove.setPreferredSize(new java.awt.Dimension(70, 20));

        buttonGroup1.add(dez);
        dez.setText("Dez");
        dez.setPreferredSize(new java.awt.Dimension(70, 20));

        buttonGroup1.add(quinze);
        quinze.setText("Quinze");
        quinze.setPreferredSize(new java.awt.Dimension(70, 20));

        buttonGroup1.add(catorze);
        catorze.setText("Catorze");
        catorze.setPreferredSize(new java.awt.Dimension(70, 20));
        catorze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catorzeActionPerformed(evt);
            }
        });

        buttonGroup1.add(treze);
        treze.setText("Treze");
        treze.setPreferredSize(new java.awt.Dimension(70, 20));

        buttonGroup1.add(doze);
        doze.setText("Doze");
        doze.setPreferredSize(new java.awt.Dimension(70, 20));

        buttonGroup1.add(onze);
        onze.setText("Onze");
        onze.setPreferredSize(new java.awt.Dimension(70, 20));

        jButton1.setText("Apostar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Acertos:");

        jTextField8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setText("Quadra");

        jLabel5.setText("Quina");

        jLabel6.setText("Mega");

        jLabel7.setText("Valor Gasto:");

        javax.swing.GroupLayout resultLayout = new javax.swing.GroupLayout(result);
        result.setLayout(resultLayout);
        resultLayout.setHorizontalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vgasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        resultLayout.setVerticalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(resultLayout.createSequentialGroup()
                        .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(resultLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vgasto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sorteioofc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(oito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(onze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(doze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(treze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(catorze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quinze, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dez, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cartao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sorteioofc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quinze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(catorze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed

    }//GEN-LAST:event_seisActionPerformed

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seteActionPerformed

    private void catorzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catorzeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catorzeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int  x = (int)(Math.random()*59+1);
      int vetor[] = new int[15];
      if(seis.isSelected()){ //se o botao 6 for selecionado, sera gerado o numero inserido de cartoes com 6 posições//
          aposta = Integer.parseInt(cartao.getText());
          for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j < 6; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 3.50;
          vgasto.setText(""+vtotal);
      }
      if(sete.isSelected()){ //se o botao 7 for selecionado, sera gerado o numero inserido de cartoes com 7 posições//
          aposta = Integer.parseInt(cartao.getText());
              for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j <7; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 24.50;
          vgasto.setText(""+vtotal);    
        }
      if(oito.isSelected()){ //se o botao 8 for selecionado, sera gerado o numero inserido de cartoes com 8 posições//
          aposta = Integer.parseInt(cartao.getText());
              for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j <8; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 98.00;
          vgasto.setText(""+vtotal);
      }
      if(nove.isSelected()){ //se o botao 9 for selecionado, sera gerado o numero inserido de cartoes com 9 posições//
          aposta = Integer.parseInt(cartao.getText());
              for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j <9; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 294.00;
          vgasto.setText(""+vtotal);
      }
      if(dez.isSelected()){ //se o botao 7 for selecionado, sera gerado o numero inserido de cartoes com 6 posições//
          aposta = Integer.parseInt(cartao.getText());
              for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j <10; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 735.00;
          vgasto.setText(""+vtotal);
      }
      if(onze.isSelected()){ //se o botao 7 for selecionado, sera gerado o numero inserido de cartoes com 6 posições//
          aposta = Integer.parseInt(cartao.getText());
              for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j <11; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 1617.00;
          vgasto.setText(""+vtotal);
      }
      if(doze.isSelected()){ //se o botao 7 for selecionado, sera gerado o numero inserido de cartoes com 6 posições//
          aposta = Integer.parseInt(cartao.getText());
              for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j <12; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 3234.00;
          vgasto.setText(""+vtotal);      
      }
      if(treze.isSelected()){ //se o botao 7 for selecionado, sera gerado o numero inserido de cartoes com 6 posições//
          aposta = Integer.parseInt(cartao.getText());
              for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j <13; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 6006.00;
          vgasto.setText(""+vtotal);
      }
      if(catorze.isSelected()){ //se o botao 7 for selecionado, sera gerado o numero inserido de cartoes com 6 posições//
          aposta = Integer.parseInt(cartao.getText());
              for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j <14; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 10510.50;
          vgasto.setText(""+vtotal);
      }
      if(quinze.isSelected()){ //se o botao 7 for selecionado, sera gerado o numero inserido de cartoes com 6 posições//
          aposta = Integer.parseInt(cartao.getText());
              for (int i = 1; i <= aposta; i++) {//laço para o numero de cartoes
              for (int j = 0; j <15; j++) {//laço para os numeros inseridos nos cartões
                  x = (int)(Math.random()*59+1);
                  vetor[j] = x;
                  if(vetor[j] == Integer.parseInt(a1.getText()) 
                          || vetor[j] == Integer.parseInt(a2.getText()) 
                          || vetor[j] == Integer.parseInt(a3.getText()) 
                          || vetor[j] == Integer.parseInt(a4.getText()) 
                          || vetor[j] == Integer.parseInt(a5.getText()) 
                          || vetor[j] == Integer.parseInt(a6.getText())){
                      acertos ++;
                      acertostotal ++;
                    }  
                  if (acertos ==4 ){quadra ++; }
                  if (acertos ==5 ){quina ++; }
                  if (acertos ==6 ){mega ++; }
                }
              JOptionPane.showMessageDialog(rootPane, "Numero de acertos no cartão "+i+": "+acertos);
              acertos  = 0;
          }
          cartoes = Integer.parseInt(cartao.getText());
          vtotal = cartoes * 17517.50;
          vgasto.setText(""+vtotal);
      }
      jTextField12.setText(""+acertostotal);
      jTextField8.setText(""+quadra);
      jTextField9.setText(""+quina);
      jTextField11.setText(""+mega);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cartao;
    private javax.swing.JRadioButton catorze;
    private javax.swing.JRadioButton dez;
    private javax.swing.JRadioButton doze;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jTextField11;
    private javax.swing.JLabel jTextField12;
    private javax.swing.JLabel jTextField8;
    private javax.swing.JLabel jTextField9;
    private javax.swing.JRadioButton nove;
    private javax.swing.JRadioButton oito;
    private javax.swing.JRadioButton onze;
    private javax.swing.JRadioButton quinze;
    private javax.swing.JPanel result;
    private javax.swing.JRadioButton seis;
    private javax.swing.JRadioButton sete;
    private javax.swing.JPanel sorteioofc;
    private javax.swing.JRadioButton treze;
    private javax.swing.JLabel vgasto;
    // End of variables declaration//GEN-END:variables
}
