/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author Victor
 */
public class TelaJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogo
     */
    int cont = 0;
    int b1=0, b2=0, b3=0, b4=0, b5=0, b6=0, b7=0, b8=0, b9=0, b10=0, b11=0, b12=0;
    int t1=0, t2=0, t3=0, t4=0, t5=0, t6=0;
    int v;
    
    public TelaJogo() {
        initComponents();
        
        jPanel1.setVisible(false); jPanel2.setVisible(false); jPanel3.setVisible(false); 
        jPanel4.setVisible(false); jPanel5.setVisible(false); jPanel6.setVisible(false); 
        jPanel7.setVisible(false); jPanel8.setVisible(false); jPanel9.setVisible(false); 
        jPanel10.setVisible(false); jPanel11.setVisible(false); jPanel12.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/1.jpg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel2 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/2.jpeg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel3 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/3.jpeg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel4 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/4.jpg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel5 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/5.jpg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel6 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/5.jpg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel7 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/3.jpeg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel8 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/6.jpg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel9 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/4.jpg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel10 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/2.jpeg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel11 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/6.jpg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        jPanel12 = new JPanel() { BufferedImage img; { try { img = ImageIO.read(getClass().getResource("/imgcampo/1.jpg")); } catch (IOException ex) { ex.printStackTrace(); } } @Override protected void paintComponent(Graphics g) { super.paintComponent(g); g.drawImage(img, 0, 0, getWidth(), getHeight(), this); } };
        n1 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        n4 = new javax.swing.JLabel();
        n5 = new javax.swing.JLabel();
        n6 = new javax.swing.JLabel();
        n7 = new javax.swing.JLabel();
        n8 = new javax.swing.JLabel();
        n9 = new javax.swing.JLabel();
        n10 = new javax.swing.JLabel();
        n11 = new javax.swing.JLabel();
        n12 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 210, 120));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 200, 120));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 210, 120));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 210, 120));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 210, 120));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 200, 120));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 210, 120));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 210, 130));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 210, 130));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 200, 130));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 200, 130));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 210, 130));

        n1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n1MouseClicked(evt);
            }
        });
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 210, 140));

        n2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n2MouseClicked(evt);
            }
        });
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 220, 140));

        n3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n3MouseClicked(evt);
            }
        });
        getContentPane().add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 210, 140));

        n4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n4MouseClicked(evt);
            }
        });
        getContentPane().add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 210, 140));

        n5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n5MouseClicked(evt);
            }
        });
        getContentPane().add(n5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 210, 140));

        n6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n6MouseClicked(evt);
            }
        });
        getContentPane().add(n6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 220, 140));

        n7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n7MouseClicked(evt);
            }
        });
        getContentPane().add(n7, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 270, 220, 140));

        n8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n8MouseClicked(evt);
            }
        });
        getContentPane().add(n8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 210, 140));

        n9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n9MouseClicked(evt);
            }
        });
        getContentPane().add(n9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 210, 140));

        n10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n10MouseClicked(evt);
            }
        });
        getContentPane().add(n10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 220, 140));

        n11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n11MouseClicked(evt);
            }
        });
        getContentPane().add(n11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 220, 140));

        n12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n12MouseClicked(evt);
            }
        });
        getContentPane().add(n12, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 210, 140));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void n12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n12MouseClicked
        if(cont == 0){
            b1=0; b2=0; b3=0; b4=0; b5=0; b6=0; b7=0; b8=0; b9=0; b10=0; b11=0;
            b12=1;
            v=12;
            jPanel12.setVisible(true);
            cont++;
        }else{
            b12=1;
            if(b12 == b1){
                t1=1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel12.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel12.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                }
            }else{
                jPanel12.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==2){
                    jPanel12.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==3){
                    jPanel12.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==4){
                    jPanel12.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==5){
                    jPanel12.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel12.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==7){
                    jPanel12.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==8){
                    jPanel12.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==9){
                    jPanel12.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==10){
                    jPanel12.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==11){
                    jPanel12.setVisible(false);
                    jPanel11.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n12MouseClicked

    private void n1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MouseClicked
        if(cont == 0){
            b2=0; b3=0; b4=0; b5=0; b6=0; b7=0; b8=0; b9=0; b10=0; b11=0; b12=0;
            b1=1;
            v = 1;
            jPanel1.setVisible(true);
            cont++;
        }else{
            b1=1;
            if(b1 == b12){
                t1=1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel1.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel1.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                }
            }else{
                jPanel1.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==2){
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==3){
                    jPanel1.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==4){
                    jPanel1.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==5){
                    jPanel1.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel1.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==7){
                    jPanel1.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==8){
                    jPanel1.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==9){
                    jPanel1.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==10){
                    jPanel1.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==11){
                    jPanel1.setVisible(false);
                    jPanel11.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n1MouseClicked

    private void n2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n2MouseClicked
        if(cont == 0){
            b1=0; b3=0; b4=0; b5=0; b6=0; b7=0; b8=0; b9=0; b10=0; b11=0; b12=0;
            b2=2;
            v=2;
            jPanel2.setVisible(true);
            cont++;
        }else{
            b2=2;
            if(b2 == b10){
                t2 = 1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel2.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel2.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                }
            }else{
                jPanel2.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel2.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==3){
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==4){
                    jPanel2.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==5){
                    jPanel2.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel2.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==7){
                    jPanel2.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==8){
                    jPanel2.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==9){
                    jPanel2.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==11){
                    jPanel2.setVisible(false);
                    jPanel11.setVisible(false);
                }else if(v==12){
                    jPanel2.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n2MouseClicked

    private void n10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n10MouseClicked
        if(cont == 0){
            b1=0; b2=0; b3=0; b4=0; b5=0; b6=0; b7=0; b8=0; b9=0; b11=0; b12=0;
            b10=2; 
            v=10;
            jPanel10.setVisible(true);
            cont++;
        }else{
            b10=2;
            if(b10 == b2){
                t2=1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel10.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel10.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;    
                }
            }else{
                jPanel10.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel10.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==3){
                    jPanel10.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==4){
                    jPanel10.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==5){
                    jPanel10.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel10.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==7){
                    jPanel10.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==8){
                    jPanel10.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==9){
                    jPanel10.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==11){
                    jPanel10.setVisible(false);
                    jPanel11.setVisible(false);
                }else if(v==12){
                    jPanel10.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n10MouseClicked

    private void n3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n3MouseClicked
        if(cont == 0){
            b1=0; b2=0; b4=0; b5=0; b6=0; b7=0; b8=0; b9=0; b10=0; b11=0; b12 = 0;
            b3 = 3;
            v = 3;
            jPanel3.setVisible(true);
            cont++;
        }else{
            b3 = 3;
            if(b3 == b7){
                t3 = 1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel3.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel3.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                }
            }else{
                jPanel3.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel3.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==2){
                    jPanel3.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==4){
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==5){
                    jPanel3.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel3.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==8){
                    jPanel3.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==9){
                    jPanel3.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==10){
                    jPanel3.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==11){
                    jPanel3.setVisible(false);
                    jPanel11.setVisible(false);
                }else if(v==12){
                    jPanel3.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n3MouseClicked

    private void n7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n7MouseClicked
        if(cont == 0){
            b1 = 0; b2=0; b3=0; b4=0; b5=0; b6=0; b8=0; b9=0; b10=0; b11=0; b12 = 0;
            b7 = 3;
            v = 7;
            jPanel7.setVisible(true);
            cont++;
        }else{
            b7 = 3;
            if(b7 == b3){
                t3 = 1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel7.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel7.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                }
            }else{
                jPanel7.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel7.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==2){
                    jPanel7.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==4){
                    jPanel7.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==5){
                    jPanel7.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel7.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==8){
                    jPanel7.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==9){
                    jPanel7.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==10){
                    jPanel7.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==11){
                    jPanel7.setVisible(false);
                    jPanel11.setVisible(false);
                }else if(v==12){
                    jPanel7.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n7MouseClicked

    private void n4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n4MouseClicked
        if(cont == 0){
            b1 = 0; b2=0; b3=0; b5=0; b6=0; b7=0; b8=0; b9=0; b10=0; b11=0; b12 = 0;
            b4 = 4;
            v = 4;
            jPanel4.setVisible(true);
            cont++;
        }else{
            b4 = 4;
            if(b4 == b9){
                t4 = 1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel4.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel4.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                }
            }else{
                jPanel4.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel4.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==2){
                    jPanel4.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==3){
                    jPanel4.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==5){
                    jPanel4.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel4.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==7){
                    jPanel4.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==8){
                    jPanel4.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==10){
                    jPanel4.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==11){
                    jPanel4.setVisible(false);
                    jPanel11.setVisible(false);
                }else if(v==12){
                    jPanel4.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n4MouseClicked

    private void n9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n9MouseClicked
        if(cont == 0){
            b1 = 0; b2=0; b3=0; b4=0; b5=0; b6=0; b7=0; b8=0; b10=0; b11=0; b12 = 0;
            b9 = 4;
            v = 9;
            jPanel9.setVisible(true);
            cont++;
        }else{
            b9 = 4;
            if(b9 == b4){
                t4 = 1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel9.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel9.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                }                
            }else{
                jPanel9.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel9.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==2){
                    jPanel9.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==3){
                    jPanel9.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==5){
                    jPanel9.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel9.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==7){
                    jPanel9.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==8){
                    jPanel9.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==10){
                    jPanel9.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==11){
                    jPanel9.setVisible(false);
                    jPanel11.setVisible(false);
                }else if(v==12){
                    jPanel9.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n9MouseClicked

    private void n5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MouseClicked
        if(cont == 0){
            b1 = 0; b2=0; b3=0; b4=0; b6=0; b7=0; b8=0; b9=0; b10=0; b11=0; b12 = 0;
            b5 = 5;
            v = 5;
            jPanel5.setVisible(true);
            cont++;
        }else{
            b5 = 5;
            if(b5 == b6){
                t5 = 1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel5.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel5.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                }                
            }else{
                jPanel5.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel5.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==2){
                    jPanel5.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==3){
                    jPanel5.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==4){
                    jPanel5.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==7){
                    jPanel5.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==8){
                    jPanel5.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==9){
                    jPanel5.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==10){
                    jPanel5.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==11){
                    jPanel5.setVisible(false);
                    jPanel11.setVisible(false);
                }else if(v==12){
                    jPanel5.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n5MouseClicked

    private void n6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n6MouseClicked
        if(cont == 0){
            b1 = 0; b2=0; b3=0; b4=0; b5=0; b6=0; b7=0; b8=0; b9=0; b10=0; b11=0; b12 = 0;
            b6 = 5;
            v = 6;
            jPanel6.setVisible(true);
            cont++;
        }else{
            b6 = 5;
            if(b6 == b5){
                t5 = 1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel6.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel6.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                } 
            }else{
                jPanel6.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel6.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==2){
                    jPanel6.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==3){
                    jPanel6.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==4){
                    jPanel6.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==7){
                    jPanel6.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==8){
                    jPanel6.setVisible(false);
                    jPanel8.setVisible(false);
                }else if(v==9){
                    jPanel6.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==10){
                    jPanel6.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==11){
                    jPanel6.setVisible(false);
                    jPanel11.setVisible(false);
                }else if(v==12){
                    jPanel6.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n6MouseClicked

    private void n8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n8MouseClicked
        if(cont == 0){
            b1 = 0; b2=0; b3=0; b4=0; b5=0; b6=0; b7=0; b9=0; b10=0; b11=0; b12 = 0;
            b8 = 6;
            v = 8;
            jPanel8.setVisible(true);
            cont++;
        }else{
            b8 = 6;
            if(b8 == b11){
                t6 = 1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel8.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel8.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                } 
            }else{
                jPanel8.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel8.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==2){
                    jPanel8.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==3){
                    jPanel8.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==4){
                    jPanel8.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==5){
                    jPanel8.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel8.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==7){
                    jPanel8.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==9){
                    jPanel8.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==10){
                    jPanel8.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==12){
                    jPanel8.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n8MouseClicked

    private void n11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n11MouseClicked
        if(cont == 0){
            b1 = 0; b2=0; b3=0; b4=0; b5=0; b6=0; b7=0; b8=0; b9=0; b10=0; b12 = 0;
            b11 = 6;
            v = 11;
            jPanel6.setVisible(true);
            cont++;
        }else{
            b11 = 6;
            if(b11 == b8){
                t6 = 1;
                if(t1 == 1 && t2 == 1 && t3 == 1 && t4 == 1 && t5 == 1 && t6 == 1){
                    jPanel11.setVisible(true);
                    parabains parabains = new parabains();
                    parabains.setVisible(true);
                }else{
                    jPanel11.setVisible(true);
                    acerto acerto = new acerto();
                    acerto.setVisible(true);
                    cont = 0;
                } 
            }else{
                jPanel11.setVisible(true);
                erro erro = new erro();
                erro.setVisible(true);
                cont = 0;
                if(v==1){
                    jPanel11.setVisible(false);
                    jPanel1.setVisible(false);
                }else if(v==2){
                    jPanel11.setVisible(false);
                    jPanel2.setVisible(false);
                }else if(v==3){
                    jPanel11.setVisible(false);
                    jPanel3.setVisible(false);
                }else if(v==4){
                    jPanel11.setVisible(false);
                    jPanel4.setVisible(false);
                }else if(v==5){
                    jPanel11.setVisible(false);
                    jPanel5.setVisible(false);
                }else if(v==6){
                    jPanel11.setVisible(false);
                    jPanel6.setVisible(false);
                }else if(v==7){
                    jPanel11.setVisible(false);
                    jPanel7.setVisible(false);
                }else if(v==9){
                    jPanel11.setVisible(false);
                    jPanel9.setVisible(false);
                }else if(v==10){
                    jPanel11.setVisible(false);
                    jPanel10.setVisible(false);
                }else if(v==12){
                    jPanel11.setVisible(false);
                    jPanel12.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_n11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n10;
    private javax.swing.JLabel n11;
    private javax.swing.JLabel n12;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel n5;
    private javax.swing.JLabel n6;
    private javax.swing.JLabel n7;
    private javax.swing.JLabel n8;
    private javax.swing.JLabel n9;
    // End of variables declaration//GEN-END:variables
}
